combined_geyser: "{% set combined_geyser = geyser %}{% if global_overrides.geyser is defined %}{% set combined_geyser = (combined_geyser | combine(global_overrides.geyser, recursive=True)) %}{% endif %}{% if node_overrides.geyser is defined %}{% set combined_geyser = (combined_geyser | combine(node_overrides.geyser, recursive=True)) %}{% endif %}{% if outer_item.plugins.geyser is defined %}{% set combined_geyser = (combined_geyser | combine(outer_item.plugins.geyser, recursive=True)) %}{% endif %}{{ combined_geyser }}"
geyser:
  above-bedrock-nether-building: false
  add-non-bedrock-items: true
  allow-custom-skulls: true
  allow-third-party-capes: true
  allow-third-party-ears: false
  always-quick-change-armor: false
  bedrock:
    address: 0.0.0.0
    clone-remote-port: false
    compression-level: 6
    enable-proxy-protocol: false
    motd1: Geyser
    motd2: Another Geyser server.
    port: 19132
    server-name: Geyser
  cache-images: 0
  command-suggestions: true
  config-version: 4
  custom-skull-render-distance: 32
  debug-mode: false
  disable-bedrock-scaffolding: false
  emote-offhand-workaround: disabled
  enable-proxy-connections: false
  floodgate-key-file: key.pem
  force-resource-packs: true
  forward-player-ping: false
  legacy-ping-passthrough: false
  log-player-ip-addresses: true
  max-players: 100
  max-visible-custom-skulls: 128
  metrics:
    enabled: true
    uuid: generateduuid
  mtu: 1400
  notify-on-new-bedrock-update: true
  passthrough-motd: false
  passthrough-player-counts: false
  passthrough-protocol-name: false
  pending-authentication-timeout: 120
  ping-passthrough-interval: 3
  remote:
    address: auto
    allow-password-authentication: true
    auth-type: online
    forward-hostname: false
    port: 25565
    use-proxy-protocol: false
  saved-user-logins:
    - ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername
    - ThisOtherExampleUsernameShouldAlsoBeLongEnough
  scoreboard-packet-threshold: 20
  show-cooldown: title
  show-coordinates: true
  use-direct-connection: true
  xbox-achievements-enabled: false
