pufferfish:
  dab:
    activation-dist-mod: 8
    blacklisted-entities: []
    enabled: false
    max-tick-freq: 20
    start-distance: 12
  enable-async-mob-spawning: true
  enable-books: true
  enable-suffocation-optimization: true
  entity_timeouts:
    LLAMA_SPIT: -1
    SNOWBALL: -1
  inactive-goal-selector-throttle: false
  info:
    version: "1.0"
  misc:
    disable-method-profiler: true
    disable-out-of-order-chat: false
  projectile:
    max-loads-per-projectile: 10
    max-loads-per-tick: 10
  sentry-dsn: ""
