# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Downloading Bedrock resource packs for {{ outer_item.name }}
  get_url:
    url: "{{ item }}"
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/Geyser-Spigot/packs/
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rw,g=r,o=r
  loop: "{{ outer_item.bedrock_resource_packs }}"
  when:
    - outer_item.bedrock_resource_packs is defined
    - outer_item.state.backup.restore_backup == false
