# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Configuring the LuckPerms users for {{ outer_item.name }}
  template:
    src: ../templates/java/plugins/LuckPerms/luckperms.yml.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/LuckPerms/{% if outer_item.plugins.luckperms.config['storage-method'] == "json" %}json{% elif outer_item.plugins.luckperms.config['storage-method'] == "yaml" %}yaml{% endif %}-storage/users/{{ item.uuid }}.{% if outer_item.plugins.luckperms.config['storage-method'] == "json" %}json{% elif outer_item.plugins.luckperms.config['storage-method'] == "yaml" %}yml{% endif %}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop: "{{ outer_item.plugins.luckperms.users }}"
  when:
    - outer_item.plugins.luckperms.config['storage-method'] == "json" or outer_item.plugins.luckperms.config['storage-method'] == "yaml"
    - outer_item.plugins.luckperms.users is defined
    - outer_item.state.backup.restore_backup == false
    - outer_item.restore_permissions

- name: Configuring the LuckPerms groups for {{ outer_item.name }}
  template:
    src: ../templates/java/plugins/LuckPerms/luckperms.yml.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/LuckPerms/{% if outer_item.plugins.luckperms.config['storage-method'] == "json" %}json{% elif outer_item.plugins.luckperms.config['storage-method'] == "yaml" %}yaml{% endif %}-storage/groups/{{ item.name }}.{% if outer_item.plugins.luckperms.config['storage-method'] == "json" %}json{% elif outer_item.plugins.luckperms.config['storage-method'] == "yaml" %}yml{% endif %}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop: "{{ outer_item.plugins.luckperms.groups }}"
  when:
    - outer_item.plugins.luckperms.config['storage-method'] == "json" or outer_item.plugins.luckperms.config['storage-method'] == "yaml"
    - outer_item.plugins.luckperms.groups is defined
    - outer_item.state.backup.restore_backup == false
    - outer_item.restore_permissions
