# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Downloading Minecraft Petal server for {{ outer_item.name }}
  get_url:
    url: https://github.com/Bloom-host/Petal/releases/download/1.19.2-{{ outer_item.build }}/petal-1.19.2.jar
    dest: /opt/minecraft/{{ outer_item.name }}/server/server.jar
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
    force: yes
