#yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Creating the plugin directories for {{ outer_item.name }}
  file:
    path: /opt/minecraft/{{ outer_item.name }}/server/plugins/{{ item.path }}
    state: "{{ item.state }}"
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0755
  loop:
    - {
      path: Chunky,
      state: directory,
    }
    - {
      path: CustomCommandPrefix,
      state: directory,
    }
    - {
      path: floodgate,
      state: directory,
    }
    - {
      path: Geyser-Spigot/packs,
      state: directory,
    }
    - {
      path: Harbor,
      state: directory,
    }
    - { path: LuckPerms, state: directory }
    - {
      path: LuckPerms/json-storage/groups,
      state: "{% if combined_luckperms.config['storage-method'] == 'json' %}directory{% else %}absent{% endif %}",
    }
    - {
      path: LuckPerms/json-storage/users,
      state: "{% if combined_luckperms.config['storage-method'] == 'json' %}directory{% else %}absent{% endif %}",
    }
    - {
      path: LuckPerms/yaml-storage/groups,
      state: "{% if combined_luckperms.config['storage-method'] == 'yaml' %}directory{% else %}absent{% endif %}",
    }
    - {
      path: LuckPerms/yaml-storage/users,
      state: "{% if combined_luckperms.config['storage-method'] == 'yaml' %}directory{% else %}absent{% endif %}",
    }
    - {
      path: MiniMOTD,
      state: directory,
    }
    - {
      path: ViaVersion,
      state: "{% if outer_item.viaversion %}directory{% else %}absent{% endif %}",
    }
    - {
      path: WorldEdit,
      state: directory,
    }
    - {
      path: WorldGuard,
      state: directory,
    }
  when:
    - outer_item.state.backup.restore_backup == false
