#yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Downloading plugins for {{ outer_item.name }}
  get_url:
    url: "{{ item.url }}"
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/{{ item.dest }}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop:
    - {
        url: "{% if outer_item.discordsrv %}{{ discordsrv_latest.stdout }}{% endif %}",
        dest: DiscordSRV.jar,
        when: "{{ outer_item.discordsrv }}",
      }
    - {
        url: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar,
        dest: Geyser-Spigot.jar,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar,
        dest: floodgate-spigot.jar,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: https://ci.opencollab.dev/job/GeyserMC/job/GeyserOptionalPack/job/master/lastSuccessfulBuild/artifact/GeyserOptionalPack.mcpack,
        dest: Geyser-Spigot/packs/,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: "{% if outer_item.harbor %}{{ harbor_latest.stdout }}{% endif %}",
        dest: Harbor.jar,
        when: "{{ outer_item.harbor }}",
      }
    - {
        url: https://cdn.discordapp.com/attachments/804019242512810034/955961417117339718/TreeAssist.jar, # this is terrible and I hate it
        dest: TreeAssist.jar,
        when: "{{ true }}",
      }
    - {
        url: "{% if outer_item.chunky %}https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/lastSuccessfulBuild/artifact/bukkit/build/libs/{{ chunky_latest.stdout }}{% endif %}",
        dest: "Chunky.jar",
        when: "{{ outer_item.chunky }}",
      }
    - {
        url: "{% if use_bluemap %}{{ bluemap_latest.stdout }}{% endif %}",
        dest: BlueMap.jar,
        when: "{{ outer_item.bluemap.use }}",
      }
    - {
        url: "{% if outer_item.bluemap.use %}{{ bluemap_floodgate_latest.stdout }}{% endif %}",
        dest: BlueMapFloodgate.jar,
        when: "{{ outer_item.bluemap.use and outer_item.geyser }}",
      }
    - {
        url: "{{ appleskin_latest.stdout }}",
        dest: AppleSkinSpigot.jar,
        when: "{{ true }}",
      }
    - {
        url: "{{ tabtps_latest.stdout }}",
        dest: tabtps.jar,
        when: "{{ true }}",
      }
    - {
        url: "https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/loader/build/libs/{{ luckperms_latest.stdout }}",
        dest: LuckPerms.jar,
        when: "{{ true }}",
      }
    - {
        url: "{% if outer_item.viaversion %}{{ viaversion_latest.stdout }}{% endif %}",
        dest: "ViaVersion.jar",
        when: "{{ outer_item.viaversion }}",
      }
    - {
        url: "{% if grafana.use %}{{ unifiedmetrics_latest.stdout }}{% endif %}",
        dest: "unifiedmetrics.jar",
        when: "{{ grafana.use }}",
      }
    - {
        url: https://media.forgecdn.net/files/3697/296/worldedit-bukkit-7.2.10.jar,
        dest: worldedit-bukkit.jar,
        when: "{{ outer_item.worldguard }}",
      }
    - {
        url: https://media.forgecdn.net/files/3677/516/worldguard-bukkit-7.0.7-dist.jar,
        dest: worldguard-bukkit.jar,
        when: "{{ outer_item.worldguard }}",
      }
  when:
    - outer_item.state.new_server or outer_item.state.update_server
    - outer_item.state.backup.restore_backup == false
    - item.when

- name: Removing plugins for {{ outer_item.name }}
  file:
    path: /opt/minecraft/{{ outer_item.name }}/server/plugins/{{ item.src }}
    state: absent
  loop:
    - { src: BlueMap.jar, when: "{{ outer_item.bluemap.use == false }}" }
    - {
        src: BlueMapFloodgate.jar,
        when: "{{ outer_item.bluemap.use == false }}",
      }
    - { src: Chunky.jar, when: "{{ outer_item.chunky == false }}" }
    - { src: CustomCommandPrefix.jar, when: "{{ outer_item.geyser == false }}" }
    - { src: DiscordSRV.jar, when: "{{ outer_item.discordsrv == false }}" }
    - { src: floodgate-spigot.jar, when: "{{ outer_item.geyser == false }}" }
    - { src: Geyser-Spigot.jar, when: "{{ outer_item.geyser == false }}" }
    - { src: Harbor.jar, when: "{{ outer_item.harbor == false }}" }
    - { src: ViaVersion.jar, when: "{{ outer_item.viaversion == false }}" }
    - {
        src: worldedit-bukkit.jar,
        when: "{{ outer_item.worldguard == false }}",
      }
    - {
        src: worldguard-bukkit.jar,
        when: "{{ outer_item.worldguard == false }}",
      }
  when: item.when

- name: Downloading custom plugins for {{ outer_item.name }}
  get_url:
    url: "{{ item.url }}"
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/{{ item.name }}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop: "{{ outer_item.custom_plugins }}"
