#yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Downloading plugins for {{ outer_item.name }}
  get_url:
    url: "{{ item.url }}"
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/{{ item.dest }}
    owner: minecraft
    group: minecraft
    mode: 0644
  loop:
    - {
        url: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar,
        dest: Geyser-Spigot.jar,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar,
        dest: floodgate-spigot.jar,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: https://ci.opencollab.dev/job/GeyserMC/job/GeyserOptionalPack/job/master/lastSuccessfulBuild/artifact/GeyserOptionalPack.mcpack,
        dest: Geyser-Spigot/packs/,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: https://cdn.discordapp.com/attachments/804019242512810034/951278280319852554/TreeAssist.jar, # this is terrible and I hate it
        dest: TreeAssist.jar,
        when: "{{ true }}",
      }
    - {
        url: "{% if outer_item.chunky %}https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/lastSuccessfulBuild/artifact/bukkit/build/libs/{{ chunky_latest.stdout }}{% endif %}",
        dest: "Chunky.jar",
        when: "{{ outer_item.chunky }}",
      }
    - {
        url: "{{ appleskin_latest.stdout }}",
        dest: AppleSkinSpigot.jar,
        when: "{{ true }}",
      }
    - {
        url: "{{ tabtps_latest.stdout }}",
        dest: tabtps.jar,
        when: "{{ true }}",
      }
    - {
        url: "{% if outer_item.geyser %}{{ floodgateplaceholders_latest.stdout }}{% endif %}",
        dest: PlaceholderAPI/expansions/FloodgatePlaceholders.jar,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: "{% if outer_item.geyser %}https://ci.extendedclip.com/job/PlaceholderAPI/lastSuccessfulBuild/artifact/build/libs/{{ placeholderapi_latest.stdout }}{% endif %}",
        dest: PlaceholderAPI.jar,
        when: "{{ outer_item.geyser }}",
      }
    - {
        url: "https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/loader/build/libs/{{ luckperms_latest.stdout }}",
        dest: LuckPerms.jar,
        when: "{{ true }}",
      }
    - {
        url: "{% if outer_item.viaversion %}{{ viaversion_latest.stdout }}{% endif %}",
        dest: "ViaVersion.jar",
        when: "{{ outer_item.viaversion }}",
      }
    - {
        url: "{% if grafana.use %}{{ unifiedmetrics_latest.stdout }}{% endif %}",
        dest: "unifiedmetrics.jar",
        when: "{{ grafana.use }}",
      }
  when:
    - outer_item.new_server or outer_item.update_server
    - outer_item.restore_backup == false
    - item.when

- name: Removing plugins for {{ outer_item.name }}
  file:
    path: /opt/minecraft/server/plugins/{{ item.src }}
    state: absent
  loop:
    - { src: Chunky.jar, when: "{{ outer_item.chunky == false }}" }
    - { src: CustomCommandPrefix.jar, when: "{{ outer_item.geyser == false }}" }
    - { src: floodgate-spigot.jar, when: "{{ outer_item.geyser == false }}" }
    - { src: Geyser-Spigot.jar, when: "{{ outer_item.geyser == false }}" }
    - { src: ViaVersion.jar, when: "{{ outer_item.viaversion == false }}" }
  when: item.when
