# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Downloading Minecraft Purpur server for {{ outer_item.name }}
  get_url:
    url: https://api.purpurmc.org/v2/purpur/1.20.1/{{ outer_item.build }}/download
    dest: /opt/minecraft/{{ outer_item.name }}/server/server.jar
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: "0644"
    force: true
