# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Getting the Minecraft Purpur checksum for {{ outer_item.name }}
  shell: curl --silent https://api.purpurmc.org/v2/purpur/1.19.2/{{ outer_item.build }} | jq -r .md5
  register: purpur_checksum

- name: Downloading Minecraft Purpur server for {{ outer_item.name }}
  get_url:
    url: https://api.purpurmc.org/v2/purpur/1.19.2/{{ outer_item.build }}/download
    dest: /opt/minecraft/{{ outer_item.name }}/server/server.jar
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
    checksum: md5:{{ purpur_checksum.stdout }}
