# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Copying scripts and systemd units for {{ outer_item.name }}
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ outer_item.name }}-bluemap.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - certbot_ready: "{{ bluemap.certbot.ready }}"
  when: "{{ outer_item.bluemap.use }}"
