#yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Creating the Paper config directory for {{ outer_item.name }}
  file:
    path: /opt/minecraft/{{ outer_item.name }}/server/config
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0755
    state: directory

- name: Creating the Paper world directories for {{ outer_item.name }}
  file:
    path: /opt/minecraft/{{ outer_item.name }}/server/{{ item.key }}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0755
    state: directory
  loop: "{{ combined_paper_worlds | dict2items }}"

- name: Configuring the Minecraft server for {{ outer_item.name }}
  template:
    src: ../templates/java/{{ item.src }}.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/{{ item.src }}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop:
    - { src: server.properties, when: "{{ true }}" }
    - { src: bukkit.yml, when: "{{ true }}" }
    - { src: commands.yml, when: "{{ true }}" }
    - { src: spigot.yml, when: "{{ true }}" }
    - { src: config/paper-global.yml, when: "{{ true }}" }
    - { src: config/paper-world-defaults.yml, when: "{{ true }}" }
    - { src: plugins/BlueMap/core.conf, when: "{{ outer_item.bluemap.use }}" }
    - { src: plugins/BlueMap/plugin.conf, when: "{{ outer_item.bluemap.use }}" }
    - { src: plugins/BlueMap/render.conf, when: "{{ outer_item.bluemap.use }}" }
    - {
        src: plugins/BlueMap/webserver.conf,
        when: "{{ outer_item.bluemap.use }}",
      }
    - { src: plugins/Chunky/config.yml, when: "{{ outer_item.chunky }}" }
    - {
        src: plugins/DiscordSRV/config.yml,
        when: "{{ outer_item.discordsrv }}",
      }
    - {
        src: plugins/FarmControl/config.yml,
        when: "{{ outer_item.farmcontrol }}",
      }
    - { src: plugins/floodgate/config.yml, when: "{{ outer_item.geyser }}" }
    - { src: plugins/Geyser-Spigot/config.yml, when: "{{ outer_item.geyser }}" }
    - { src: plugins/Harbor/config.yml, when: "{{ outer_item.harbor }}" }
    - { src: plugins/LuckPerms/config.yml, when: "{{ true }}" }
    - { src: plugins/LPC/config.yml, when: "{{ true }}" }
    - { src: plugins/MiniMOTD/main.conf, when: "{{ outer_item.minimotd }}" }
    - {
        src: plugins/MiniMOTD/plugin_settings.conf,
        when: "{{ outer_item.minimotd }}",
      }
    - { src: plugins/TreeAssist/config.yml, when: "{{ true }}" }
    - { src: plugins/TreeAssist/trees/default.yml, when: "{{ true }}" }
    - { src: plugins/UnifiedMetrics/driver/prometheus.yml, when: true }
    - {
        src: plugins/ViaVersion/config.yml,
        when: "{{ outer_item.viaversion }}",
      }
    - {
        src: plugins/ViewDistanceTweaks/config.yml,
        when: "{{ outer_item.viewdistancetweaks }}",
      }
    - {
        src: plugins/WorldEdit/config.yml,
        when: "{{ outer_item.worldedit or outer_item.worldguard }}",
      }
    - {
        src: plugins/WorldGuard/config.yml,
        when: "{{ outer_item.worldguard }}",
      }
  when:
    - outer_item.state.backup.restore_backup == false
    - item.when

- name: Configuring the Paper world settings for {{ outer_item.name }}
  template:
    src: ../templates/java/config/paper-world.yml.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/{{ item.key }}/paper-world.yml
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop: "{{ combined_paper_worlds | dict2items }}"
  when:
    - outer_item.state.backup.restore_backup == false

- name: Configuring custom plugins for {{ outer_item.name }}
  copy:
    src: ../files/java/{{ outer_item.name }}/custom-plugins/{{ item.name }}
    dest: /opt/minecraft/{{ outer_item.name }}/server/plugins/
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rwX,g=rX,o=rX
  loop: "{{ outer_item.custom_plugins.plugins }}"
  when:
    - outer_item.custom_plugins.use
    - item.config

- name: Copying the server permissions files for {{ outer_item.name }}
  template:
    src: ../templates/java/{{ item }}.json.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/{{ item }}.json
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: 0644
  loop:
    - ops
    - whitelist
  when:
    - outer_item.restore_permissions
    - outer_item.state.backup.restore_backup == false
