#yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

- name: Creating the Paper config directory for {{ outer_item.name }}
  file:
    path: /opt/minecraft/{{ outer_item.name }}/server/config
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: Creating the Paper world directories for {{ outer_item.name }}
  file:
    path: /opt/minecraft/{{ outer_item.name }}/server/{{ item.key }}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rwX,g=rX,o=rX
    state: directory
  loop: "{{ combined_paper_worlds | dict2items }}"

- name: Configuring the Minecraft server for {{ outer_item.name }}
  template:
    src: ../templates/java/{{ item.src }}.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/{{ item.src }}
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rw,g=r,o=r
  loop:
    - { src: server.properties, when: true }
    - { src: bukkit.yml, when: true }
    - { src: commands.yml, when: true }
    - { src: spigot.yml, when: true }
    - { src: config/paper-global.yml, when: true }
    - { src: config/paper-world-defaults.yml, when: true }
    - { src: plugins/Chunky/config.yml, when: true }
    - { src: plugins/floodgate/config.yml, when: true }
    - { src: plugins/Geyser-Spigot/config.yml, when: true }
    - { src: plugins/Harbor/config.yml, when: true }
    - { src: plugins/LuckPerms/config.yml, when: true }
    - {
      src: plugins/ViaVersion/config.yml,
      when: "{{ outer_item.viaversion }}",
    }
    - {
      src: plugins/WorldEdit/config.yml,
      when: true,
    }
    - {
      src: plugins/WorldGuard/config.yml,
      when: true,
    }
  when:
    - outer_item.state.backup.restore_backup == false
    - item.when

- name: Configuring the Paper world settings for {{ outer_item.name }}
  template:
    src: ../templates/java/config/paper-world.yml.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/{{ item.key }}/paper-world.yml
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rw,g=r,o=r
  loop: "{{ combined_paper_worlds | dict2items }}"
  when:
    - outer_item.state.backup.restore_backup == false

- name: Copying the server permissions files for {{ outer_item.name }}
  template:
    src: ../templates/java/{{ item }}.json.j2
    dest: /opt/minecraft/{{ outer_item.name }}/server/{{ item }}.json
    owner: minecraft-{{ outer_item.name }}
    group: minecraft-{{ outer_item.name }}
    mode: u=rw,g=r,o=r
  loop:
    - ops
    - whitelist
  when:
    - outer_item.restore_permissions
    - outer_item.state.backup.restore_backup == false
