- name: Copying systemd services for {{ outer_item.name }}
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  when: item.when
  loop:
    - {
        src: "../templates/systemd/service.j2",
        dest: "/etc/systemd/system/minecraft-{{ outer_item.name }}.service",
        owner: root,
        mode: "0644",
        description: "Minecraft Server - {{ outer_item.name }}",
        type: "forking",
        execstartpre: "{% if outer_item.server_icon.random %}-/opt/minecraft/server-icon.sh{% endif %}",
        execstart: "/usr/bin/tmux new-session -s minecraft-{{ outer_item.name }} -d '{{ command }}'",
        execstop: "/opt/minecraft/stop.sh {{ outer_item.name }}",
        workingdirectory: "/opt/minecraft/{{ outer_item.name }}/server",
        nice: "-20",
        oomscoreadjust: "-1000",
        restart: on-failure,
        user: "minecraft-{{ outer_item.name }}",
        group: "minecraft-{{ outer_item.name }}",
        when: true,
      }
    - {
        src: "../templates/scripts/continuous-deployment.sh.j2",
        dest: "/opt/minecraft/{{ outer_item.name }}/continuous-deployment.sh",
        owner: root,
        mode: "0744",
        when: "{{ outer_item.state.continuous_deployment.enabled }}",
      }
