- name: Copying systemd services for {{ outer_item.name }}
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - {
        src: "../templates/scripts/start.sh.j2",
        dest: "/opt/minecraft/{{ outer_item.name }}/start.sh",
        owner: "root",
        mode: "0755",
        when: true,
      }
    - {
        src: "../templates/systemd/service.j2",
        dest: "/etc/systemd/system/minecraft-{{ outer_item.name }}.service",
        owner: root,
        mode: "0644",
        description: "Minecraft Server - {{ outer_item.name }}",
        type: "forking",
        execstartpre: "{% if outer_item.server_icon.random %}-/opt/minecraft/server-icon.sh{% endif %}",
        execstart: "/opt/minecraft/{{ outer_item.name }}/start.sh",
        execstop: "/opt/minecraft/stop.sh {{ outer_item.name }}",
        pidfile: "/run/minecraft/{{ outer_item.name }}",
        workingdirectory: "/opt/minecraft/{{ outer_item.name }}/server",
        nice: "-20",
        oomscoreadjust: "-1000",
      }
