- name: Copying systemd services for {{ outer_item.name }}
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  when: item.when
  loop:
    - {
      src: "../templates/systemd/service.j2",
      dest: "/etc/systemd/system/minecraft-{{ outer_item.name }}.service",
      owner: root,
      mode: "u=rw,g=r,o=r",
      description: "Minecraft Server - {{ outer_item.name }}",
      type: "forking",
      execstart: "/usr/bin/tmux new-session -s minecraft-{{ outer_item.name }} -d '{{ command }}'",
      execstop: "/opt/minecraft/stop.sh {{ outer_item.name }}",
      workingdirectory: "/opt/minecraft/{{ outer_item.name }}/server",
      nice: "-20",
      oomscoreadjust: "-1000",
      restart: on-failure,
      user: "minecraft-{{ outer_item.name }}",
      group: "minecraft-{{ outer_item.name }}",
      when: true,
    }
