# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

 - hosts: bedrockconnect
   vars:
      domains:
       - domain: "hivebedrock.network"
         subdomain:
          - "geo"
          - "@"
       - domain: "mineplex.com"
         subdomain:
          - "mco"
       - domain: "inpvp.net"
         subdomain:
          - "play"
       - domain: "lbsg.net"
         subdomain:
          - "mco"
       - domain: "cubecraft.net"
         subdomain:
          - "mco"
       - domain: "galaxite.net"
         subdomain:
          - "play"
       - domain: "pixelparadise.gg"
         subdomain:
          - "play"

   tasks:

    - name: Setting the timezone
      timezone:
         name: "{{ timezone }}"

    - name: Installing packages
      dnf:
         name:
          - bind
          - java-11-openjdk-headless
          - jq
         state: present
         update_cache: yes

    - name: Creating the minecraft user
      user:
         name: minecraft
         shell: /bin/bash

    - name: Creating the bedrockconnect directory
      file:
         path: /home/minecraft/bedrockconnect
         state: directory
         owner: minecraft
         group: minecraft
         mode: 0755

    - name: Gathering Facts about services
      service_facts:

    - name: Stopping the existing server
      systemd:
         name: bedrockconnect
         state: stopped
      when:
       - ansible_facts.services['minecraft-' + edition + '.service'] is defined

    - name: Getting the latest BedrockConnect release
      shell: curl --silent "https://api.github.com/repos/Pugmatt/BedrockConnect/releases/latest" | jq -r '.assets[] | select(.name == "BedrockConnect-1.0-SNAPSHOT.jar").browser_download_url'
      register: bedrockconnect_latest

    - name: Downloading BedrockConnect
      get_url:
         url: "{{ bedrockconnect_latest.stdout }}"
         dest: /home/minecraft/bedrockconnect/BedrockConnect.jar
         owner: minecraft
         group: minecraft
         mode: 0644

    - name: Copying the BedrockConnect custom server list
      template:
         src: files/bedrockconnect/custom_servers.json
         dest: /home/minecraft/bedrockconnect/
         owner: minecraft
         group: minecraft
         mode: 0644

    - name: Copying the BIND9 zones
      template:
         src: templates/bedrockconnect/db.j2
         dest: /var/named/db.{{ item.domain }}
         owner: root
         group: root
         mode: 0644
      with_items: "{{ domains }}"

    - name: Copying the BIND9 configuration
      copy:
         src: files/bedrockconnect/named.conf.local
         dest: /etc/named/
         owner: root
         group: root
         mode: 0644

    - name: Copying scripts and systemd units
      template:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: "{{ item.owner }}"
         group: "{{ item.owner }}"
         mode: "{{ item.mode }}"
      with_items:
       - { src: "templates/dnf-reboot.sh.j2", dest: "/home/minecraft/dnf-reboot.sh", owner: "minecraft", mode: "0755" }
       - { src: "files/disk-utilization.sh", dest: "/home/minecraft/", owner: "minecraft", mode: "0755" }
       - { src: "templates/systemd/minecraft.service.j2", dest: "/etc/systemd/system/bedrockconnect.service", owner: "root", mode: "0644" }
       - { src: "files/systemd/dnf-upgrade.service", dest: "/etc/systemd/system/dnf-upgrade.service", owner: "root", mode: "0644" }
       - { src: "files/systemd/dnf-upgrade.timer", dest: "/etc/systemd/system/dnf-upgrade.timer", owner: "root", mode: "0644" }
       - { src: "files/systemd/oci-disk-utilization.service", dest: "/etc/systemd/system/oci-disk-utilization.service", owner: "root", mode: "0644" }
       - { src: "files/systemd/oci-disk-utilization.timer", dest: "/etc/systemd/system/oci-disk-utilization.timer", owner: "root", mode: "0644" }

    - name: Starting the systemd units
      systemd:
         name: "{{ item }}"
         state: started
         enabled: yes
         daemon_reload: yes
      with_items:
       - bedrockconnect.service
       - named.service
       - dnf-upgrade.timer
       - oci-disk-utilization.timer
