# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

 - hosts: all

   tasks:

    - name: Setting the timezone
      timezone:
         name: "{{ timezone }}"

    - name: Removing the Oracle Cloud iptables rules
      lineinfile:
         path: /etc/iptables/rules.v4
         search_string: "-A INPUT -j REJECT --reject-with icmp-host-prohibited"
         line: "#-A INPUT -j REJECT --reject-with icmp-host-prohibited"
      register: iptables

    - name: Reloading iptables
      shell: iptables-restore < /etc/iptables/rules.v4
      when: iptables.changed

    - name: Adding the OpenJDK PPA
      apt_repository:
         repo: ppa:openjdk-r/ppa

    - name: Installing packages
      apt:
         name:
          - openjdk-16-jre-headless
          - python3-pip
          - jq
         state: present
         update_cache: yes

    - name: Creating the minecraft user
      user:
         name: minecraft
         shell: /bin/bash

    - name: Gathering Facts about services
      service_facts:
      when:
       - new_server == "true" or update_server == "true"

    - name: Stopping the existing server
      systemd:
         name: minecraft-{{ edition }}
         state: stopped
      when:
       - new_server == "true" or update_server == "true"
       - ansible_facts.services['minecraft-' + edition + '.service'] is defined

    - name: Removing the existing server
      file:
         path: /home/minecraft/{{ edition }}
         state: absent
      when: new_server == "true"

    - name: Creating the server directory
      file:
         path: /home/minecraft/{{ edition }}
         state: directory
         owner: minecraft
         group: minecraft
         mode: 0755
      when: new_server == "true"

    - name: Backing up the existing server
      shell: tar cfO - {{ edition }} | gzip --best | oci os object put --auth instance_principal --bucket-name {{ bucket_name }} --file - --name "{{ edition }}.tar.gz" --force
      args:
         chdir: /home/minecraft
      when: update_server == "true"

    - name: Getting a list of Paper builds
      uri:
         url: https://papermc.io/api/v2/projects/paper/versions/{{ version }}
         method: GET
         headers:
            accept: application/json
         return_content: true
      register: paper_builds
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Getting the latest Paper build
      shell: echo '{{ paper_builds.content }}' | jq ".builds | max"
      register: paper_latest
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading Minecraft Paper server
      get_url:
         url: https://papermc.io/api/v2/projects/paper/versions/{{ version }}/builds/{{ paper_latest.stdout }}/downloads/paper-{{ version }}-{{ paper_latest.stdout }}.jar
         dest: /home/minecraft/{{ edition }}/server.jar
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Copying the server.properties file
      copy:
         src: files/java/server.properties
         dest: /home/minecraft/{{ edition }}/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Copying the server permissions files
      copy:
         src: files/java/{{ item }}.json
         dest: /home/minecraft/{{ edition }}/
         owner: minecraft
         group: minecraft
         mode: 0644
      with_items:
       - ops
       - whitelist
      when:
       - restore_permissions == "true"

    - name: Configuring the Paper server
      copy:
         src: files/java/spigot.yml
         dest: /home/minecraft/{{ edition }}/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Creating the Geyser plugin directories
      file:
         path: /home/minecraft/geyser/plugins/{{ item }}
         state: directory
         owner: minecraft
         group: minecraft
         mode: 0755
      with_items:
       - CustomCommandPrefix
       - floodgate
       - Geyser-Spigot/packs
      when:
       - edition == "geyser"
       - new_server == "true"
       - restore_backup == "false"

    - name: Downloading the Geyser plugin
      get_url:
         url: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar
         dest: /home/minecraft/geyser/plugins/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Configuring the Geyser plugin
      copy:
         src: files/java/geyser/config.yml
         dest: /home/minecraft/geyser/plugins/Geyser-Spigot/config.yml
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the Floodgate plugin
      get_url:
         url: https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar
         dest: /home/minecraft/geyser/plugins/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Configuring the Floodgate plugin
      copy:
         src: files/java/geyser/floodgate/config.yml
         dest: /home/minecraft/geyser/plugins/floodgate/config.yml
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the CustomCommandPrefix plugin
      copy:
         src: files/CustomCommandPrefix-1.0.jar
         dest: /home/minecraft/geyser/plugins/CustomCommandPrefix.jar
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Configuring the CustomCommandPrefix plugin
      copy:
         content: "prefix: '?'"
         dest: /home/minecraft/geyser/plugins/CustomCommandPrefix/config.yml
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the GeyserOptionalPack resource pack
      get_url:
         url: https://ci.opencollab.dev/job/GeyserMC/job/GeyserOptionalPack/job/master/lastSuccessfulBuild/artifact/GeyserOptionalPack.mcpack
         dest: /home/minecraft/geyser/plugins/Geyser-Spigot/packs/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Installing the OCI client
      pip:
         name: oci-cli

    - name: Downloading the latest server backup
      command: oci os object get --auth instance_principal --bucket-name {{ bucket_name }} --file {{ edition }}.tar.gz --name {{ edition }}.tar.gz
      args:
         chdir: /home/minecraft
      when:
       - restore_backup == "true"
       - backup_version == ""

    - name: Downloading the server backup
      command: oci os object get --auth instance_principal --bucket-name {{ bucket_name }} --file {{ edition }}.tar.gz --name {{ edition }}.tar.gz --version-id {{ backup_version }}
      args:
         chdir: /home/minecraft
      when:
       - restore_backup == "true"
       - backup_version | length > 0

    - name: Restoring the server backup
      unarchive:
         src: /home/minecraft/{{ edition }}.tar.gz
         dest: /home/minecraft/
         owner: minecraft
         group: minecraft
         mode: u=rwX,g=rX,o=rX
         remote_src: yes
      when: restore_backup == "true"

    - name: Removing the downloaded backup
      file:
         path: /home/minecraft/{{ edition }}.tar.gz
         state: absent
      when: restore_backup == "true"

    - name: Copying the Minecraft server scripts
      template:
         src: templates/{{ item }}.sh.j2
         dest: /home/minecraft/{{ item }}_{{ edition }}.sh
         owner: minecraft
         group: minecraft
         mode: 0755
      with_items:
       - stop
       - backup

    - name: Copying the OS scripts
      copy:
         src: files/{{ item }}.sh
         dest: /home/minecraft/
         owner: minecraft
         group: minecraft
         mode: 0755
      with_items:
       - apt-reboot
       - disk-utilization

    - name: Copying the systemd units
      template:
         src: "{{ item.type }}/systemd/{{ item.src }}"
         dest: /etc/systemd/system/{{ item.dest }}
         owner: root
         group: root
         mode: 0644
      with_items:
       - { src: "minecraft.service.j2", dest: "minecraft-{{ edition }}.service", type: "templates" }
       - { src: "minecraft-backup.service.j2", dest: "minecraft-{{ edition }}-backup.service", type: "templates" }
       - { src: "minecraft-backup.timer.j2", dest: "minecraft-{{ edition }}-backup.timer", type: "templates" }
       - { src: "apt-upgrade.service", dest: "apt-upgrade.service", type: "files" }
       - { src: "apt-upgrade.timer", dest: "apt-upgrade.timer", type: "files" }
       - { src: "oci-disk-utilization.service", dest: "oci-disk-utilization.service", type: "files" }
       - { src: "oci-disk-utilization.timer", dest: "oci-disk-utilization.timer", type: "files" }

    - name: Accepting the Minecraft Server EULA
      copy:
         content: eula=true
         dest: /home/minecraft/{{ edition }}/eula.txt
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - new_server == "true"
       - restore_backup == "false"
       - eula == "true"

    - name: Starting the systemd units
      systemd:
         name: "{{ item }}"
         state: started
         enabled: yes
         daemon_reload: yes
      with_items:
       - minecraft-{{ edition }}.service
       - minecraft-{{ edition }}-backup.timer
       - apt-upgrade.timer
       - oci-disk-utilization.timer
