# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json

 - hosts: java

   tasks:

    - name: Setting the timezone
      timezone:
         name: "{{ timezone }}"

    - name: Enabling EPEL
      yum_repository:
         name: ol8_developer_EPEL
         description: Oracle Linux $releasever EPEL Packages for Development ($basearch)
         baseurl: https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/developer/EPEL/$basearch/
         gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
         gpgcheck: 1
         file: oracle-epel-ol8
         enabled: true

    - name: Installing packages
      dnf:
         name:
          - java-latest-openjdk-headless
          - jq
          - tmux
         state: present
         update_cache: yes

    - name: Creating the minecraft user
      user:
         name: minecraft
         shell: /bin/bash

    - name: Gathering Facts about services
      service_facts:
      when:
       - new_server == "true" or update_server == "true"

    - name: Stopping the existing server
      systemd:
         name: minecraft-{{ edition }}
         state: stopped
      when:
       - new_server == "true" or update_server == "true"
       - ansible_facts.services['minecraft-' + edition + '.service'] is defined

    - name: Removing the existing server
      file:
         path: /home/minecraft/{{ edition }}
         state: absent
      when: new_server == "true"

    - name: Creating the server directory
      file:
         path: /home/minecraft/{{ edition }}
         state: directory
         owner: minecraft
         group: minecraft
         mode: 0755
      when: new_server == "true"

    - name: Backing up the existing server
      shell: tar cfO - {{ edition }} | gzip --best | oci os object put --auth instance_principal --bucket-name {{ bucket_name }} --file - --name "{{ edition }}.tar.gz" --force
      args:
         chdir: /home/minecraft
      when: update_server == "true"

    - name: Getting the latest Paper build
      shell: curl --silent https://papermc.io/api/v2/projects/paper/versions/{{ version }} | jq ".builds | max"
      register: paper_latest
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading Minecraft Paper server
      get_url:
         url: https://papermc.io/api/v2/projects/paper/versions/{{ version }}/builds/{{ paper_latest.stdout }}/downloads/paper-{{ version }}-{{ paper_latest.stdout }}.jar
         dest: /home/minecraft/{{ edition }}/server.jar
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Configuring the Minecraft server
      copy:
         src: files/java/{{ item }}
         dest: /home/minecraft/{{ edition }}/
         owner: minecraft
         group: minecraft
         mode: 0644
      with_items:
       - server.properties
       - spigot.yml
       - paper.yml
      when:
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Copying the server permissions files
      copy:
         src: files/java/{{ item }}.json
         dest: /home/minecraft/{{ edition }}/
         owner: minecraft
         group: minecraft
         mode: 0644
      with_items:
       - ops
       - whitelist
      when:
       - restore_permissions == "true"
       - update_server == "false"
       - restore_backup == "false"

    - name: Creating the Geyser plugin directories
      file:
         path: /home/minecraft/geyser/plugins/{{ item }}
         state: directory
         owner: minecraft
         group: minecraft
         mode: 0755
      with_items:
       - CustomCommandPrefix
       - floodgate
       - Geyser-Spigot/packs
      when:
       - edition == "geyser"
       - new_server == "true"
       - restore_backup == "false"

    - name: Downloading the Geyser plugin
      get_url:
         url: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar
         dest: /home/minecraft/geyser/plugins/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Configuring the Geyser plugin
      copy:
         src: files/java/geyser/config.yml
         dest: /home/minecraft/geyser/plugins/Geyser-Spigot/config.yml
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the Floodgate plugin
      get_url:
         url: https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar
         dest: /home/minecraft/geyser/plugins/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the CustomCommandPrefix plugin
      copy:
         src: files/CustomCommandPrefix-1.0.jar
         dest: /home/minecraft/geyser/plugins/CustomCommandPrefix.jar
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Configuring the CustomCommandPrefix plugin
      copy:
         content: "prefix: '?'"
         dest: /home/minecraft/geyser/plugins/CustomCommandPrefix/config.yml
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the GeyserOptionalPack resource pack
      get_url:
         url: https://ci.opencollab.dev/job/GeyserMC/job/GeyserOptionalPack/job/master/lastSuccessfulBuild/artifact/GeyserOptionalPack.mcpack
         dest: /home/minecraft/geyser/plugins/Geyser-Spigot/packs/
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - edition == "geyser"
       - new_server == "true" or update_server == "true"
       - restore_backup == "false"

    - name: Downloading the latest server backup
      command: oci os object get --auth instance_principal --bucket-name {{ bucket_name }} --file {{ edition }}.tar.gz --name {{ edition }}.tar.gz
      args:
         chdir: /home/minecraft
      when:
       - restore_backup == "true"
       - backup_version == ""

    - name: Downloading the server backup
      command: oci os object get --auth instance_principal --bucket-name {{ bucket_name }} --file {{ edition }}.tar.gz --name {{ edition }}.tar.gz --version-id {{ backup_version }}
      args:
         chdir: /home/minecraft
      when:
       - restore_backup == "true"
       - backup_version | length > 0

    - name: Restoring the server backup
      unarchive:
         src: /home/minecraft/{{ edition }}.tar.gz
         dest: /home/minecraft/
         owner: minecraft
         group: minecraft
         mode: u=rwX,g=rX,o=rX
         remote_src: yes
      when: restore_backup == "true"

    - name: Removing the downloaded backup
      file:
         path: /home/minecraft/{{ edition }}.tar.gz
         state: absent
      when: restore_backup == "true"

    - name: Copying firewall rule, scripts, and systemd units
      template:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: "{{ item.owner }}"
         group: "{{ item.owner }}"
         mode: "{{ item.mode }}"
      with_items:
       - { src: "files/minecraft.xml", dest: "/etc/firewalld/services/", owner: "root", mode: "0644" }
       - { src: "templates/dnf-reboot.sh.j2", dest: "/home/minecraft/dnf-reboot.sh", owner: "minecraft", mode: "0755" }
       - { src: "templates/stop.sh.j2", dest: "/home/minecraft/stop_{{ edition }}.sh", owner: "minecraft", mode: "0755" }
       - { src: "templates/backup.sh.j2", dest: "/home/minecraft/backup_{{ edition }}.sh", owner: "minecraft", mode: "0755" }
       - { src: "files/disk-utilization.sh", dest: "/home/minecraft/", owner: "minecraft", mode: "0755" }
       - { src: "templates/systemd/minecraft.service.j2", dest: "/etc/systemd/system/minecraft-{{ edition }}.service", owner: "root", mode: "0644" }
       - { src: "templates/systemd/minecraft-backup.service.j2", dest: "/etc/systemd/system/minecraft-{{ edition }}-backup.service", owner: "root", mode: "0644" }
       - { src: "templates/systemd/minecraft-backup.timer.j2", dest: "/etc/systemd/system/minecraft-{{ edition }}-backup.timer", owner: "root", mode: "0644" }
       - { src: "files/systemd/dnf-upgrade.service", dest: "/etc/systemd/system/dnf-upgrade.service", owner: "root", mode: "0644" }
       - { src: "files/systemd/dnf-upgrade.timer", dest: "/etc/systemd/system/dnf-upgrade.timer", owner: "root", mode: "0644" }
       - { src: "files/systemd/oci-disk-utilization.service", dest: "/etc/systemd/system/oci-disk-utilization.service", owner: "root", mode: "0644" }
       - { src: "files/systemd/oci-disk-utilization.timer", dest: "/etc/systemd/system/oci-disk-utilization.timer", owner: "root", mode: "0644" }

    - name: Accepting the Minecraft Server EULA
      copy:
         content: eula=true
         dest: /home/minecraft/{{ edition }}/eula.txt
         owner: minecraft
         group: minecraft
         mode: 0644
      when:
       - new_server == "true"
       - restore_backup == "false"
       - eula == "true"

    - name: Setting SELinux to permissive (will fix)
      selinux:
         policy: targeted
         state: permissive

    - name: Reloading firewalld
      command: firewall-cmd --reload

    - name: Allowing Minecraft through the firewall
      firewalld:
         service: minecraft
         state: enabled
         permanent: yes
         immediate: yes

    - name: Starting the systemd units
      systemd:
         name: "{{ item }}"
         state: started
         enabled: yes
         daemon_reload: yes
      with_items:
       - minecraft-{{ edition }}.service
       - minecraft-{{ edition }}-backup.timer
       - dnf-upgrade.timer
       - oci-disk-utilization.timer
