 - hosts: all

   tasks:

    - name: Setting the timezone to Europe/London
      timezone:
         name: Europe/London

    - name: Removing the Oracle Cloud iptables rules
      lineinfile:
         path: /etc/iptables/rules.v4
         search_string: "-A INPUT -j REJECT --reject-with icmp-host-prohibited"
         line: "#-A INPUT -j REJECT --reject-with icmp-host-prohibited"
      register: iptables

    - name: Reloading iptables
      shell: iptables-restore < /etc/iptables/rules.v4
      when: iptables.changed

    - name: Preventing cloud-init from overwriting /etc/apt/sources.list
      lineinfile:
         path: /etc/cloud/cloud.cfg
         line: "apt_preserve_sources_list: true"
      when: edition = bedrock

    - name: Enabling AMD64 apt repositories
      copy:
         src: files/arch
         dest: /var/lib/dpkg/arch
         owner: root
         group: root
         mode: 0644
      when: edition = bedrock

    - name: Adding AMD64 apt repositories
      copy:
         src: files/sources.list
         dest: /etc/apt/sources.list
         owner: root
         group: root
         mode: 0644
      when: edition = bedrock

    - name: Installing packages
      apt:
         name:
          - unzip
          - qemu-user
          - libc6:amd64
          - zlib1g:amd64
          - libssl1.1:amd64
          - libstdc++6:amd64
          - python3-pip
         state: present
         update_cache: yes
      when: edition = bedrock

    - name: Installing packages
      apt:
         name: default-jre-headless
         state: present
         update_cache: yes
      when: edition = java

    - name: Creating the minecraft user
      user:
         name: minecraft
         shell: /bin/nologin

    - name: Creating the server directory
      file:
         path: /home/minecraft/{{ edition }}
         state: directory
         owner: minecraft
         group: minecraft
         mode: 0755

    - name: Extracting Minecraft Bedrock server
      unarchive:
         src: https://minecraft.azureedge.net/bin-linux/bedrock-server-1.16.221.01.zip
         dest: /home/minecraft/bedrock/
         owner: minecraft
         group: minecraft
         mode: u=rwX,g=rX,o=rX
         remote_src: yes
      when: edition = bedrock

    - name: Downloading Minecraft Java server
      get_url:
         url: https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar
         dest: /home/minecraft/java/server.jar
         owner: minecraft
         group: minecraft
         mode: 0644
      when: edition = java

    - name: Making the Bedrock server executable
      file:
         path: /home/minecraft/bedrock/bedrock_server
         mode: 0755
      when: edition = bedrock

    - name: Copying the server scripts
      template:
         src: templates/{{ item }}.sh.j2
         dest: /home/minecraft/{{ item }}_edition.sh
         owner: minecraft
         group: minecraft
         mode: 0755
      with_items:
       - stop
       - backup

    - vars:
         command: "/home/minecraft/bedrock/bedrock_server"
      when: edition = bedrock
    - vars:
         command: "java -Xmx1024M -Xms1024M -jar server.jar nogui"
      when: edition = java

    - name: Copying the systemd units
      template:
         src: "{{ item.type }}/systemd/{{ item.src }}"
         dest: /etc/systemd/system/{{ item.dest }}
         owner: root
         group: root
         mode: 0644
      with_items:
       - { src: "minecraft.service.j2", dest: "minecraft-{{ edition }}.service", type: "templates" }
       - { src: "minecraft-backup.service.j2", dest: "minecraft-{{ edition }}-backup.service", type: "templates" }
       - { src: "minecraft-backup.timer.j2", dest: "minecraft-{{ edition }}-backup.timer", type: "templates" }
       - { src: "apt-upgrade.service", dest: "apt-upgrade.service", type: "files" }
       - { src: "apt-upgrade.timer", dest: "apt-upgrade.timer", type: "files" }

    - name: Starting the systemd units
      systemd:
         name: "{{ item }}"
         state: started
         enabled: yes
         daemon_reload: yes
      with_items:
       - minecraft-{{ edition }}.service
       - minecraft-{{ edition }}-backup.timer
       - apt-upgrade.timer

    - name: Installing the OCI client
      pip:
         name: oci-cli
